### PR TITLE
fix encoding for Windows

### LINKED ISSUE #189: Encoding error when Installing IRuby kernelspec in Jupyter directory on Windows.
### Steps to reproduce

Install iruby gem from github master. 
```bash
gem specific_install http://github.com/SciRuby/iruby
```

Type register command.

```bash
iruby register
```

Then get an error. 

```console
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/iruby-0.3/lib/iruby/jupyter.rb:11:in `join': 
path name must be ASCII-compatible (UTF-16LE): 
"C:\\Users\\Kojix2\\AppData\\Roaming" 
(Encoding::CompatibilityError)
```

### PR DESCRIPTION
**Pull request by kojix2**
Fix #189

### CODE REVIEW

File: lib/iruby/jupyter.rb [hunk 1]
```diff
@@ -37,7 +37,7 @@ def windows_user_appdata
         case call_SHGetFolderPathW(Fiddle::NULL, csidl_appdata, Fiddle::NULL, 0, path)
         when 0
           len = (1 ... (path.size/2)).find {|i| path[2*i, 2] == "\0\0" }
-          path = path.to_str(2*len).force_encoding(Encoding::UTF_16LE)
+          path = path.to_str(2*len).force_encoding(Encoding::UTF_16LE).encode(Encoding::UTF_8)
```
Comment (mrkn) [inline lib/iruby/jupyter.rb]: You can write `encode(Encoding::UTF_8, Encoding::UTF_16LE)`.
